language: rust
rust: stable
os: linux
cache: cargo

branches:
  only:
    - master

install:
  - rustup component add rustfmt
  - rustup component add clippy-preview

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo build --release
  - cargo test
  - cargo test --release
  - cargo doc --no-deps
